//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualStudioSnippetsCollectza {
  using System;


  /// <summary>
  ///   一个强类型的资源类，用于查找本地化的字符串等。
  /// </summary>
  // 此类是由 StronglyTypedResourceBuilder
  // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
  // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
  // (以 /str 作为命令选项)，或重新生成 VS 项目。
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  public class snippets {

    private static global::System.Resources.ResourceManager resourceMan;

    private static global::System.Globalization.CultureInfo resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal snippets() {
    }

    /// <summary>
    ///   返回此类使用的缓存的 ResourceManager 实例。
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager {
      get {
        if (object.ReferenceEquals(resourceMan, null)) {
          global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisualStudioSnippetsCollectza.snippets", typeof(snippets).Assembly);
          resourceMan = temp;
        }
        return resourceMan;
      }
    }

    /// <summary>
    ///   重写当前线程的 CurrentUICulture 属性
    ///   重写当前线程的 CurrentUICulture 属性。
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture {
      get {
        return resourceCulture;
      }
      set {
        resourceCulture = value;
      }
    }

    /// <summary>
    ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
    ///&lt;CodeSnippets xmlns=&quot;http://schemas.microsoft.com/VisualStudio/2005/CodeSnippet&quot;&gt;
    ///  &lt;CodeSnippet Format=&quot;1.0.0&quot;&gt;
    ///    &lt;Header&gt;
    ///      &lt;Title&gt;()&lt;/Title&gt;
    ///      &lt;Shortcut&gt;90&lt;/Shortcut&gt;
    ///      &lt;Description&gt;运算优先级&lt;/Description&gt;
    ///      &lt;Author&gt;ZhuYuZi&lt;/Author&gt;
    ///      &lt;SnippetTypes&gt;
    ///        &lt;SnippetType&gt;Expansion&lt;/SnippetType&gt;
    ///        &lt;SnippetType&gt;SurroundsWith&lt;/SnippetType&gt;
    ///      &lt;/SnippetTypes&gt;
    ///    &lt;/Header&gt;
    ///    &lt;Snippet&gt;
    ///      &lt;Declarations&gt;
    ///      &lt;/Declarations&gt;
    /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    public static string __ {
      get {
        return ResourceManager.GetString("__", resourceCulture);
      }
    }

    /// <summary>
    ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
    ///&lt;CodeSnippets xmlns=&quot;http://schemas.microsoft.com/VisualStudio/2005/CodeSnippet&quot;&gt;
    ///  &lt;CodeSnippet Format=&quot;1.0.0&quot;&gt;
    ///    &lt;Header&gt;
    ///      &lt;Title&gt;(())&lt;/Title&gt;
    ///      &lt;Shortcut&gt;9900&lt;/Shortcut&gt;
    ///      &lt;Description&gt;强制转换&lt;/Description&gt;
    ///      &lt;Author&gt;ZhuYuZi&lt;/Author&gt;
    ///      &lt;SnippetTypes&gt;
    ///        &lt;SnippetType&gt;Expansion&lt;/SnippetType&gt;
    ///        &lt;SnippetType&gt;SurroundsWith&lt;/SnippetType&gt;
    ///      &lt;/SnippetTypes&gt;
    ///    &lt;/Header&gt;
    ///    &lt;Snippet&gt;
    ///      &lt;Declarations&gt;
    ///        &lt;Literal&gt;
    /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    public static string @__explicit__ {
      get {
        return ResourceManager.GetString("__explicit__", resourceCulture);
      }
    }

    /// <summary>
    ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
    ///&lt;CodeSnippets xmlns=&quot;http://schemas.microsoft.com/VisualStudio/2005/CodeSnippet&quot;&gt;
    ///  &lt;CodeSnippet Format=&quot;1.0.0&quot;&gt;
    ///    &lt;Header&gt;
    ///      &lt;Title&gt;as_is&lt;/Title&gt;
    ///      &lt;Shortcut&gt;asoris&lt;/Shortcut&gt;
    ///      &lt;Description&gt;转换与类型检查&lt;/Description&gt;
    ///      &lt;Author&gt;ZhuYuZi&lt;/Author&gt;
    ///      &lt;SnippetTypes&gt;
    ///        &lt;SnippetType&gt;Expansion&lt;/SnippetType&gt;
    ///        &lt;SnippetType&gt;SurroundsWith&lt;/SnippetType&gt;
    ///      &lt;/SnippetTypes&gt;
    ///    &lt;/Header&gt;
    ///    &lt;Snippet&gt;
    ///      &lt;Declarations&gt;
    ///        &lt;Lite [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    public static string asOris {
      get {
        return ResourceManager.GetString("asOris", resourceCulture);
      }
    }

    /// <summary>
    ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
    ///&lt;CodeSnippets xmlns=&quot;http://schemas.microsoft.com/VisualStudio/2005/CodeSnippet&quot;&gt;
    ///  &lt;CodeSnippet Format=&quot;1.0.0&quot;&gt;
    ///    &lt;Header&gt;
    ///      &lt;Title&gt;unitydebug&lt;/Title&gt;
    ///      &lt;Shortcut&gt;udb&lt;/Shortcut&gt;
    ///      &lt;Description&gt;UnityDebug 语句的代码片段&lt;/Description&gt;
    ///      &lt;Author&gt;ZhuYuZi&lt;/Author&gt;
    ///      &lt;SnippetTypes&gt;
    ///        &lt;SnippetType&gt;Expansion&lt;/SnippetType&gt;
    ///        &lt;SnippetType&gt;SurroundsWith&lt;/SnippetType&gt;
    ///      &lt;/SnippetTypes&gt;
    ///    &lt;/Header&gt;
    ///    &lt;Snippet&gt;
    ///      &lt;Declarations&gt;
    /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    public static string Debug {
      get {
        return ResourceManager.GetString("Debug", resourceCulture);
      }
    }

    /// <summary>
    ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
    ///&lt;CodeSnippets xmlns=&quot;http://schemas.microsoft.com/VisualStudio/2005/CodeSnippet&quot;&gt;
    ///  &lt;CodeSnippet Format=&quot;1.0.0&quot;&gt;
    ///    &lt;Header&gt;
    ///      &lt;Title&gt;unitydebug&lt;/Title&gt;
    ///      &lt;Shortcut&gt;udb&lt;/Shortcut&gt;
    ///      &lt;Description&gt;UnityDebug 语句的代码片段&lt;/Description&gt;
    ///      &lt;Author&gt;ZhuYuZi&lt;/Author&gt;
    ///      &lt;SnippetTypes&gt;
    ///        &lt;SnippetType&gt;Expansion&lt;/SnippetType&gt;
    ///        &lt;SnippetType&gt;SurroundsWith&lt;/SnippetType&gt;
    ///      &lt;/SnippetTypes&gt;
    ///    &lt;/Header&gt;
    ///    &lt;Snippet&gt;
    ///      &lt;Declarations&gt;
    /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    public static string FullDebug {
      get {
        return ResourceManager.GetString("FullDebug", resourceCulture);
      }
    }

    /// <summary>
    ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
    ///&lt;CodeSnippets xmlns=&quot;http://schemas.microsoft.com/VisualStudio/2005/CodeSnippet&quot;&gt;
    ///  &lt;CodeSnippet Format=&quot;1.0.0&quot;&gt;
    ///    &lt;Header&gt;
    ///      &lt;Title&gt;Surround&lt;/Title&gt;
    ///      &lt;Shortcut&gt;Surround&lt;/Shortcut&gt;
    ///      &lt;Description&gt;包围内容&lt;/Description&gt;
    ///      &lt;Author&gt;ZhuYuZi&lt;/Author&gt;
    ///      &lt;SnippetTypes&gt;
    ///        &lt;SnippetType&gt;Expansion&lt;/SnippetType&gt;
    ///        &lt;SnippetType&gt;SurroundsWith&lt;/SnippetType&gt;
    ///      &lt;/SnippetTypes&gt;
    ///    &lt;/Header&gt;
    ///    &lt;Snippet&gt;
    ///      &lt;Declarations&gt;
    ///        &lt;Li [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    public static string surrondwith {
      get {
        return ResourceManager.GetString("surrondwith", resourceCulture);
      }
    }
  }
}
